server:
  port: 10020

spring:
  application:
    name: lcn-oss

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

oss:
  file-root-path: D:/home/jeepay/upload
  file-public-path: ${oss.file-root-path}/public
  file-private-path: ${oss.file-root-path}/private

#  service-type: local
  service-type: aliyun-oss

  aliyun-oss:

    endpoint: oss-cn-hangzhou.aliyuncs.com
    public-bucket-name: ellabook-public
    private-bucket-name: ellabook-private
    access-key-id: xxxxxx
    access-key-secret: xxxxxx

logging:
  level:
    root: info
    com.dl.user.mapper: DEBUG
    org.springframework.web: ERROR
    org.springframework: ERROR