server:
  port: 10021

spring:
  application:
    name: lcn-easyexcel

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxx
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/



logging:
  level:
    root: info
    com.dl.user.mapper: DEBUG
    org.springframework.web: ERROR
    org.springframework: ERROR