server:
  port: 1006

spring:
  application:
    name: lcn-file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.10.43:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    min-idle-per-key: 5
upload:
  baseUrl: http://192.168.10.43/