server:
  port: 1001

spring:
  application:
    name: lcn-order

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.119.49:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ellabook
    password: Ellabook@13579
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    password: 961230
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20
    ssl: false


mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070


async:
  executor:
    thread:
      core_pool_size: 8
      max_pool_size: 9
      queue_capacity: 99999
      name:
        prefix: async-service-

redisson:
  address: redis://127.0.0.1:6379
  password: 961230
  database: 1
  timeout: 10000

rocketmq:
  namesrvAddr: 192.168.10.17:9876
  groupName: ${spring.application.name}
  sendMsgTimeoutMillis: 3000
  reconsumeTimes: 3